{{- $name := include "service.name" (dict "release" $.Release.Name "name" "peppol-directory-cache") | kebabcase | lower -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  selector:
    app: {{ $name }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000